info={
    "name":"Imroj","age":25,"Subjects":["maths","Software"],"id":2026,2:'gf'
}
print(info["Subjects"])
print(info.keys())
print(info.values())
print(info.items())
print(info.get("age"))
info.update({"city":"Feni"})
print(info)
